# fly.toml app configuration file generated for currenclever-api on 2025-04-26T14:34:28+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'currenclever-api'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT='8000'
  DB_HOST='ballast.proxy.rlwy.net'
  DB_PORT='19572'
  DB_NAME='railway'
  DB_USER='root'
  DB_PASS='WNgnXQcJDKLHIlOzyiZohpjfrcXKONae'
  DB_CHARSET = 'utf8mb4'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
